/* Auto generated by arch/../tools/offset.c at Apr 20 2002. Do not edit. */
#ifndef ASM_OFFSET_H
#define ASM_OFFSET_H 1
#define tsk_state 0
#define tsk_flags 8
#define tsk_sigpending 16
#define tsk_addr_limit 24
#define tsk_need_resched 40
#define tsk_exec_domain 32
#define tsk_ptrace 48
#define tsk_cpu 60
#define tsk_need_resched 40
#define tsk_thread 960
#define pda_kernelstack 0
#define pda_oldrsp 8
#define pda_pcurrent 24
#define pda_irqrsp 16
#define pda_irqcount 32
#define pda_pgd_quick 40
#define pda_pmd_quick 48
#define pda_pte_quick 56
#define pda_pgtable_cache_sz 64
#define pda_cpunumber 36
#define pda_irqstackptr 72
#define pda_level4_pgt 80
#ifdef __ASSEMBLY__
#define PT_TRACESYS 2
#define TASK_SIZE 548682072064
#define SIGCHLD 17
#define CLONE_VFORK 16384
#define CLONE_VM 256
#define thread_flags 56
#define ASM_THREAD_IA32 1
#endif
#endif
