name: Build vib
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files
      run: |
            sudo cp -r ./build/vib-r8168-8.052.01 /build

    - name: Run vibauthor
      run: |
            docker run -itd -v /build:/build --name vibauthor lamw/vibauthor bash

    - name: Build
      run: |
            docker exec vibauthor bash -c "
            cd /build
            vibauthor -C -t ./vib-8168-8.052.01 --force
            "
    
    - name: Upload vib
      uses: actions/upload-artifact@main
      with:
        name: r8168-vib
        path: /build
    