name: Build vib
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files
      run: |
            sudo mkdir -p /build/vib-r8168
            sudo cp -r ./vib-r8168 /build/vib-r8168

    - name: Run vibauthor
      run: |
            docker run --rm -itd -v /build:/build --name vibauthor lamw/vibauthor bash

    - name: Build
      run: |
            docker exec vibauthor bash -c "
            cd /build
            vibauthor -C -t vib-8168 -v r8168.vib -O r8168-offline-bundle.zip -f
            "
    
    - name: Upload vib
      uses: actions/upload-artifact@main
      with:
        name: vib-8168
        path: /build
    