name: Build iso
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install VMware PowerCLI
      shell: pwsh
      run: |
            Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
            Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Force -Confirm:$false -AllowClobber
    
    - name: Check
      shell: pwsh
      run: |
            Get-Module -ListAvailable VMware.PowerCLI

    