name: Build
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Run centos7
      run: |
            docker run -itd -v /build:/build --name centos7 centos:7 bash
    
    - name: Initialization environment
      run: |
            docker exec centos7 sh -c "
            sed -i '/^#/! s|^mirrorlist=|#mirrorlist=|' /etc/yum.repos.d/CentOS-Base.repo
            sed -i 's|^#baseurl=http://mirror.centos.org/centos/\$releasever/|baseurl=https://vault.centos.org/7.9.2009/|g' /etc/yum.repos.d/CentOS-Base.repo
            yum update -y
            yum install git -y
            yum groupinstall 'Development Tools' -y
            git clone https://github.com/realganfan/compile-vmkdriver-env-builder.git
            cd compile-vmkdriver-env-builder
            bash build--esxi-driver-env-centos7.sh
            "

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: original-build
        path: /build

    - name: Checkout code
      run: |
            docker exec centos7 sh -c "
            git clone https://github.com/mufeng05/r8168-esxi.git
            "

    - name: Copy files
      run: |
            docker exec centos7 sh -c "
            cp ./r8168-esxi/build-script/build-r8168.sh /build/vmkdrivers-gpl/
            cp -r ./r8168-esxi/r8168 /build/vmkdrivers-gpl/vmkdrivers/src_9/drivers/net
            "

    - name: Build
      run: |
            docker exec centos7 sh -c "
            cd /build/vmkdrivers-gpl
            bash build-r8168.sh
            "
    
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: build
        path: /build
    