name: Build r8168
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files
      run: |
            sudo cp -r ./build /
            sudo cp ./build-script/build-r8168.sh /build/vmkdrivers-gpl/
            sudo cp -r ./r8168 /build/vmkdrivers-gpl/vmkdrivers/src_9/drivers/net

    - name: Run centos7
      run: |
            docker run -itd -v /build:/build --name centos7 centos:7 bash

    - name: Build
      run: |
            docker exec centos7 bash -c "
            cd /build/vmkdrivers-gpl
            bash build-r8168.sh
            "
    
    - name: Upload r8168
      uses: actions/upload-artifact@main
      with:
        name: r8168
        path: /build/vmkdrivers-gpl/r8168
    