name: Build iso
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install VMware PowerCLI
      shell: pwsh
      run: |
            Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
            Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Force -Confirm:$false -AllowClobber
    
    - name: Download zip
      shell: pwsh
      run: |
            Invoke-WebRequest -Uri "https://github.com/mufeng05/r8168-esxi/releases/download/ESXi670-202503001/ESXi670-202503001.zip" -OutFile "ESXi670-202503001.zip"
            ls

    - name: Create ISO with driver
      shell: pwsh
      run: |
            Add-EsxSoftwareDepot "ESXi670-202503001.zip"
            Add-EsxSoftwareDepot "vib-r8168.zip"
            Start-Sleep 2
            $imageProfile = (Get-EsxImageProfile |
            Where-Object { $_.Name -like "ESXi-$baseESXiVer*-standard*" } |
            Sort-Object -Property CreationTime -Descending |
            Select-Object -First 1).Name
            $newProfileName = $($imageProfile.Replace("standard", "r8168"))
            $newProfile = New-EsxImageProfile -CloneProfile $imageProfile -name $newProfileName
            Set-EsxImageProfile -ImageProfile $newProfile -AcceptanceLevel CommunitySupported
            Add-EsxSoftwarePackage -ImageProfile $newProfile -SoftwarePackage "net55-r8168" -Force
            Export-ESXImageProfile -ImageProfile $newProfile -ExportToIso -filepath "$newProfileName.iso" -Force

    