name: Build vib
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files
      run: |
            sudo cp -r ./vib-r8168 /vib-r8168

    - name: Run vibauthor
      run: |
            docker run --rm -itd -v /vib-r8168:/vib-r8168 --name vibauthor lamw/vibauthor bash

    - name: Build
      run: |
            docker exec vibauthor bash -c "
            vibauthor -C -t /vib-8168
            "
    
    - name: Upload vib
      uses: actions/upload-artifact@main
      with:
        name: vib-8168
        path: /vib-r8168
    